version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: users_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: |
      postgres -c 'max_connections=200'
    networks:
      - users-network

  users-app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: users_app
    ports:
      - "8082:8082"
      - "1314:1314"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - CONFIG_FILE=config.docker.yaml
    command: ["/bin/sh", "-c", "./main migrate --config config.docker.yaml && ./main server --config config.docker.yaml"]
    networks:
      - users-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  users-network:
    driver: bridge